CREATE TABLE T20I (
    Team1	VARCHAR(50),
    Team2	VARCHAR(50),
    Winner	VARCHAR(50),
    Margin	VARCHAR(50),
    MatchDate	DATE,
    Ground	VARCHAR(50)
);


INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'West Indies', '5 wickets', '2024-11-16', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Pakistan', 'Australia', '13 runs', '2024-11-16', 'Sydney');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '135 runs', '2024-11-15', 'Johannesburg');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '3 wickets', '2024-11-14', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Pakistan', 'Australia', '29 runs', '2024-11-14', 'Brisbane');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '11 runs', '2024-11-13', 'Centurion');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '7 wickets', '2024-11-10', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'South Africa', '3 wickets', '2024-11-10', 'Gqeberha');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'New Zealand', 'New Zealand', '5 runs', '2024-11-10', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '8 wickets', '2024-11-09', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'New Zealand', 'Sri Lanka', '4 wickets', '2024-11-09', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '61 runs', '2024-11-08', 'Durban');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'Sri Lanka', '9 wickets', '2024-10-17', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'Sri Lanka', '73 runs', '2024-10-15', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'West Indies', '5 wickets', '2024-10-13', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '133 runs', '2024-10-12', 'Hyderabad');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '86 runs', '2024-10-09', 'Delhi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '7 wickets', '2024-10-06', 'Gwalior');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Nepal', 'Canada', '4 wickets', '2024-10-01', 'King City (NW)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'South Africa', 'Ireland', '10 runs', '2024-09-29', 'Abu Dhabi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Nepal', 'Canada', '14 runs', '2024-09-28', 'King City (NW)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'South Africa', 'South Africa', '8 wickets', '2024-09-27', 'Abu Dhabi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Australia', 'England', '3 wickets', '2024-09-13', 'Cardiff');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Australia', 'Australia', '28 runs', '2024-09-11', 'Southampton');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '6 wickets', '2024-09-07', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '70 runs', '2024-09-06', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '7 wickets', '2024-09-04', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '8 wickets', '2024-08-27', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'U.S.A.', 'U.S.A.', '20 runs', '2024-08-27', 'The Hague');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '30 runs', '2024-08-25', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '7 wickets', '2024-08-23', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'tied', '-', '2024-07-30', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'India', '7 wickets', '2024-07-28', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'India', '43 runs', '2024-07-27', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '42 runs', '2024-07-14', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '10 wickets', '2024-07-13', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '23 runs', '2024-07-10', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '100 runs', '2024-07-07', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'Zimbabwe', '13 runs', '2024-07-06', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'South Africa', 'India', '7 runs', '2024-06-29', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'India', 'India', '68 runs', '2024-06-27', 'Providence');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'South Africa', 'South Africa', '9 wickets', '2024-06-26', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Bangladesh', 'Afghanistan', '8 runs', '2024-06-24', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'India', 'India', '24 runs', '2024-06-24', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'South Africa', '3 wickets', '2024-06-23', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'U.S.A.', 'England', '10 wickets', '2024-06-23', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Australia', 'Afghanistan', '21 runs', '2024-06-22', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'India', 'India', '50 runs', '2024-06-22', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'U.S.A.', 'West Indies', '9 wickets', '2024-06-21', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'South Africa', 'South Africa', '7 runs', '2024-06-21', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Bangladesh', 'Australia', '28 runs', '2024-06-20', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'India', 'India', '47 runs', '2024-06-20', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '8 wickets', '2024-06-19', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'U.S.A.', 'South Africa', '18 runs', '2024-06-19', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'Afghanistan', 'West Indies', '104 runs', '2024-06-17', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Nepal', 'Bangladesh', '21 runs', '2024-06-16', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '3 wickets', '2024-06-16', 'Lauderhill');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Scotland', 'Australia', '5 wickets', '2024-06-15', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Namibia', 'England', '41 runs', '2024-06-15', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Nepal', 'South Africa', 'South Africa', '1 run', '2024-06-14', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'New Zealand', 'West Indies', '13 runs', '2024-06-12', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'India', 'India', '7 wickets', '2024-06-12', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Namibia', 'Australia', '9 wickets', '2024-06-11', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Pakistan', 'Pakistan', '7 wickets', '2024-06-11', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'South Africa', 'South Africa', '4 runs', '2024-06-10', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Pakistan', 'India', '6 runs', '2024-06-09', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'England', 'Australia', '36 runs', '2024-06-08', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Bangladesh', '2 wickets', '2024-06-07', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'New Zealand', 'Afghanistan', '84 runs', '2024-06-07', 'Providence');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Ireland', 'Canada', '12 runs', '2024-06-07', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Pakistan', 'tied', '-', '2024-06-06', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Ireland', 'India', '8 wickets', '2024-06-05', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Scotland', 'no result', '-', '2024-06-04', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'Sri Lanka', 'South Africa', '6 wickets', '2024-06-03', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Canada', 'U.S.A.', '7 wickets', '2024-06-01', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Pakistan', 'England', '7 wickets', '2024-05-30', 'The Oval');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '8 wickets', '2024-05-26', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '16 runs', '2024-05-25', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'Bangladesh', '10 wickets', '2024-05-25', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Pakistan', 'England', '23 runs', '2024-05-25', 'Birmingham');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '28 runs', '2024-05-23', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'U.S.A.', '6 runs', '2024-05-23', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'U.S.A.', '5 wickets', '2024-05-21', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '6 wickets', '2024-05-14', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '7 wickets', '2024-05-12', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Zimbabwe', '8 wickets', '2024-05-12', 'Mirpur');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Ireland', '5 wickets', '2024-05-10', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '5 runs', '2024-05-10', 'Mirpur');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '9 runs', '2024-05-07', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '6 wickets', '2024-05-05', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '8 wickets', '2024-05-03', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'Pakistan', '9 runs', '2024-04-27', 'Lahore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'New Zealand', '4 runs', '2024-04-25', 'Lahore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'New Zealand', '7 wickets', '2024-04-21', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'Pakistan', '7 wickets', '2024-04-20', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'no result', '-', '2024-04-18', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Afghanistan', '57 runs', '2024-03-18', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Afghanistan', '10 runs', '2024-03-17', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Ireland', '38 runs', '2024-03-15', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Sri Lanka', '28 runs', '2024-03-09', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Bangladesh', '8 wickets', '2024-03-06', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Sri Lanka', '3 runs', '2024-03-04', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '27 runs', '2024-02-25', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '72 runs', '2024-02-23', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Afghanistan', '3 runs', '2024-02-21', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '6 wickets', '2024-02-21', 'Wellington');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Sri Lanka', '72 runs', '2024-02-19', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Sri Lanka', '4 runs', '2024-02-17', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'West Indies', '37 runs', '2024-02-13', 'Perth');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'Australia', '34 runs', '2024-02-11', 'Adelaide');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'Australia', '11 runs', '2024-02-09', 'Hobart');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'Pakistan', '42 runs', '2024-01-21', 'Christchurch');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '7 wickets', '2024-01-19', 'Christchurch');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Sri Lanka', '9 wickets', '2024-01-18', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'tied', '-', '2024-01-17', 'Bengaluru');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '45 runs', '2024-01-17', 'Dunedin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Zimbabwe', '4 wickets', '2024-01-16', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'India', '6 wickets', '2024-01-14', 'Indore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Sri Lanka', '3 wickets', '2024-01-14', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '21 runs', '2024-01-14', 'Hamilton');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '46 runs', '2024-01-12', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'India', '6 wickets', '2024-01-11', 'Mohali');